//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ABCat.DB.Entity.Catalog
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CatalogContainer : DbContext
    {
        public CatalogContainer()
            : base("name=CatalogContainer")
        {
            this.Configuration.LazyLoadingEnabled = false;
        }
    
        public DbSet<Record> RecordSet { get; set; }
        public DbSet<RecordGroup> RecordGroupSet { get; set; }
        public DbSet<RecordType> RecordTypeSet { get; set; }
        public DbSet<RecordUserData> RecordUserDataSet { get; set; }
    }
}
