//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ABCat.DB.Entity.Catalog
{
    using System;
    using System.Collections.Generic;
    
    public partial class RecordGroup
    {
        public RecordGroup()
        {
            this.Records = new HashSet<Record>();
        }
    
        public int ID { get; set; }
        public string Key { get; set; }
        public string Title { get; set; }
        public Nullable<System.DateTime> LastUpdate { get; set; }
        public int RecordTypeID { get; set; }
    
        public virtual RecordType RecordType { get; set; }
        public virtual ICollection<Record> Records { get; set; }
    }
}
