//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ABCat.DB.Entity.Catalog
{
    using System;
    using System.Collections.Generic;
    
    public partial class RecordUserData
    {
        public int ID { get; set; }
        public string LocalPath { get; set; }
        public bool IsLoaded { get; set; }
        public bool IsHidden { get; set; }
        public int RecordID { get; set; }
    
        public virtual Record Record { get; set; }
    }
}
