//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ABCat.DB.Entity.Catalog
{
    using System;
    using System.Collections.Generic;
    
    public partial class RecordType
    {
        public RecordType()
        {
            this.RecordGroup = new HashSet<RecordGroup>();
        }
    
        public int ID { get; set; }
        public string Title { get; set; }
    
        public virtual ICollection<RecordGroup> RecordGroup { get; set; }
    }
}
