//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Data.Common;

namespace ABCat.DB.Entity.PageStorage
{
	using System;
	using System.Data.Entity;
	using System.Data.Entity.Infrastructure;

	public partial class PageStorageContainer : DbContext
	{
		public PageStorageContainer(DbConnection connection)
			: base(connection, true)
		{
		}

		protected override void OnModelCreating(DbModelBuilder modelBuilder)
		{
		}

		public DbSet<Page> PageSet { get; set; }
	}
}
