//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ABCat.DB.Entity.PageStorage
{
	using System;
	using System.Collections.Generic;

	public partial class Page
	{
		public string Id { get; set; }
		[Column("PageData", TypeName = "image")]
		[MaxLength]
		public byte[] PageData { get; set; }
	}
}