//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ABCat.DB.Entity.ProcessingSettings
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReplacementString
    {
        public int ID { get; set; }
        public string PossibleValue { get; set; }
        public string RecordPropertyName { get; set; }
        public string ReplaceValue { get; set; }
    }
}
