//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#pragma warning disable 1573
namespace ABCat.DB.Entity.UserData
{
    using System;
    using System.Data.Common;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class UserDataContainer : DbContext
    {
        static UserDataContainer()
    	{ 
    		Database.SetInitializer<UserDataContainer>(null);
    	}
    	
    	public UserDataContainer() : base("name=UserDataContainer")
        {
        }
    	
    	public UserDataContainer(string nameOrConnectionString) : base(nameOrConnectionString)
    	{	
    	}
    
    	public UserDataContainer(string nameOrConnectionString, DbCompiledModel model) : base(nameOrConnectionString, model)
    	{
    	}
    
    	public UserDataContainer(DbConnection existingConnection, bool contextOwnsConnection) : base(existingConnection, contextOwnsConnection)
    	{
    	}
    
    	public UserDataContainer(DbConnection existingConnection, DbCompiledModel model, bool contextOwnsConnection) : base(existingConnection, model, contextOwnsConnection)
    	{
    	}
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {		
    		modelBuilder.Configurations.Add(new HiddenRecord_Mapping());
    		modelBuilder.Configurations.Add(new RecordUserData_Mapping());
        }
    	
        public DbSet<RecordUserData> RecordUserDataSet { get; set; }
        public DbSet<HiddenRecord> HiddenRecordSet { get; set; }
    }
}
