//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using ABCat.DB.Entity.Catalog;

#pragma warning disable 1573
namespace ABCat.DB.Entity.UserData
{
	using System;
	using System.Data.Common;
	using System.Data.Entity;
	using System.Data.Entity.Infrastructure;

	[DbConfigurationType(typeof(MyConfiguration))]
	public partial class UserDataContainer : DbContext
	{
		public UserDataContainer(DbConnection connection)
			: base(connection, true)
		{
		}
	}
}
